version: '3.9'
services:
  app:
    image: node:16.13.0-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oostaoo-smart-scrapper-app
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - 'db'
      - 'cache'
      - 'mq'
    volumes:
      - './public:/app/public'
      - './src:/app/src'
      - './___tests___:/app/___tests___'

  db:
    container_name: oostaoo-smart-scrapper-db
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDATABASE
    ports:
      - '5432:5432'
    volumes:
      - ./data/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    restart: always

  cache:
    container_name: oostaoo-smart-scrapper-cache
    image: redis:7.0-alpine3.17
    ports:
      - '6379:6379'
    restart: always

  mq:
    container_name: oostaoo-smart-scrapper-mq
    image: rabbitmq:3.12-rc-management-alpine
    environment:
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_VHOST: $RABBITMQ_DEFAULT_VHOST
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: always
